### ISSUE TITLE
Proportional task dynamics does not work

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/tvm#15]
If I change `tvm::task_dynamics::PD` to `tvm::task_dynamics::P` in the following lines, the robot posture does not change (task does not work).
https://github.com/mmurooka/tmp_sources/blob/master/tvm_samples/src/TvmIkSample.cpp#L210-L215
Could you tell why that happens?
(Since the program is for the purpose of geometrical posture generation, `DynamicFunction` is not added in this example.)

**Comment by aescande** [comment]
So if you change only on those lines, you are mixing tasks expressed in velocity and tasks expressed in acceleration, meaning your problem is both on `\dot{q}`  and `\ddot{q}`.
I thought I had a check on that, and I'm actually not sure of what happens when you mix this way.

If your goal is to do IK, you should have all your tasks expressed in velocity, which means using only `task_dynamics` of order one. So:
 - make all your `task_dynamics::PD` become `task_dynamics::P`
 - remove the `dt_` argument in your `task_dynamics::VelocityDamper`
That should do the trick.

**Comment by mmurooka** [comment]
Thank you. You mean updating source codes like this: https://github.com/mmurooka/tmp_sources/commit/17a693f956d1c21fc50ecbca689ae7be1a924431.
But the program behavior does not change (robot posture is not updated).

**Comment by mmurooka** [comment]
I found that [Robot::updateTimeDependency](https://github.com/jrl-umi3218/tvm/blob/master/src/Robot.cpp#L156-L171) is only for second order case (i.e., ddq is variable).
Now the program works with first order case by integrating dq: https://github.com/mmurooka/tmp_sources/commit/9ea59bf6341f23717eeb18e9428da6b333ef430f, and I close this issue.

By the way, the following two lines seem unnecessary.
https://github.com/jrl-umi3218/tvm/blob/master/src/Robot.cpp#L165
https://github.com/jrl-umi3218/tvm/blob/master/src/Robot.cpp#L168
>     dq_.value(dq);
>     q_.value(q);
